name: Setup Ollama
description: Install Ollama and pull required models with caching
inputs:
  model:
    description: 'Ollama model to pull'
    required: false
    default: 'gpt-oss:20b'

runs:
  using: composite
  steps:
    - name: Cache Ollama binary
      id: cache-ollama-binary
      uses: actions/cache@v4
      with:
        path: ./.ollama-install
        key: ${{ runner.os }}-ollama-binary-v2

    - name: Cache Ollama models
      id: cache-ollama-models
      uses: actions/cache@v4
      with:
        path: ~/.ollama
        key: ${{ runner.os }}-ollama-${{ inputs.model }}-v2

    - name: Install Ollama binary (cache miss)
      if: steps.cache-ollama-binary.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Downloading Ollama binary..."
        ARCH=$(uname -m)
        case "$ARCH" in
            x86_64) ARCH="amd64" ;;
            aarch64|arm64) ARCH="arm64" ;;
            *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
        esac
        curl -L https://ollama.com/download/ollama-linux-${ARCH}.tgz -o ollama.tgz
        mkdir -p .ollama-install
        tar -C .ollama-install -xzf ollama.tgz
        rm ollama.tgz
        echo "Ollama binary downloaded"

    - name: Add Ollama to PATH
      shell: bash
      run: |
        echo "$(pwd)/.ollama-install/bin" >> $GITHUB_PATH

    - name: Start Ollama server
      shell: bash
      run: |
        echo "Starting Ollama server..."
        ollama start &
        sleep 2
        echo "Ollama server started"

    - name: Verify Ollama
      shell: bash
      run: |
        ollama --version

    - name: Pull model (cache miss)
      if: steps.cache-ollama-models.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Cache miss - pulling model ${{ inputs.model }}..."
        ollama pull ${{ inputs.model }}
        echo "Model pulled successfully"

    - name: Verify cache (cache hit)
      if: steps.cache-ollama-models.outputs.cache-hit == 'true'
      shell: bash
      run: |
        echo "Cache hit - models restored from cache"
        ls -lh "$HOME/.ollama" || echo "Warning: .ollama directory not found"
