[package]
name = "cmux"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.4"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.28"
ropey = "1.6"
tokio = { version = "1.41", features = ["full"] }
