name: "Setup Cmux"
description: "Setup Bun and install dependencies with caching"
runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Get Bun version
      id: bun-version
      shell: bash
      run: echo "version=$(bun --version)" >> $GITHUB_OUTPUT

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ runner.arch }}-bun-${{ steps.bun-version.outputs.version }}-node-modules-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-bun-${{ steps.bun-version.outputs.version }}-node-modules-

    - name: Cache bun install cache
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-cache-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-cache-

    - name: Cache ImageMagick (macOS)
      if: runner.os == 'macOS'
      id: cache-imagemagick-mac
      uses: actions/cache@v4
      with:
        path: |
          /opt/homebrew/Cellar/imagemagick
          /usr/local/Cellar/imagemagick
        key: ${{ runner.os }}-${{ runner.arch }}-imagemagick-7.1.1

    - name: Cache apt packages (Linux)
      if: runner.os == 'Linux'
      id: cache-apt
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-imagemagick-v1

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile

    - name: Install ImageMagick (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        if [ "${{ steps.cache-imagemagick-mac.outputs.cache-hit }}" == "true" ]; then
          echo "âœ… ImageMagick restored from cache"
          # Link the cached installation
          brew link --overwrite --force imagemagick 2>/dev/null || true
          if command -v magick &>/dev/null; then
            magick --version | head -1
          else
            echo "âš ï¸  Cache restored but linking failed, reinstalling..."
            HOMEBREW_NO_AUTO_UPDATE=1 brew install imagemagick
            magick --version | head -1
          fi
        else
          echo "ðŸ“¦ Installing ImageMagick..."
          HOMEBREW_NO_AUTO_UPDATE=1 brew install imagemagick
          magick --version | head -1
        fi

    - name: Install ImageMagick (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        if command -v convert &>/dev/null; then
          echo "âœ… ImageMagick already installed"
          convert --version | head -1
        else
          echo "ðŸ“¦ Installing ImageMagick..."
          # Restore apt cache permissions if cache was restored
          if [ "${{ steps.cache-apt.outputs.cache-hit }}" == "true" ]; then
            sudo chmod -R 755 /var/cache/apt/archives 2>/dev/null || true
          fi
          # Update only if needed and install with minimal dependencies
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends imagemagick
          convert --version | head -1
        fi
