name: "Setup Cmux"
description: "Setup Bun and install dependencies with caching"
inputs:
  install-imagemagick:
    description: "Install ImageMagick (needed for electron-builder icon generation)"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Get Bun version
      id: bun-version
      shell: bash
      run: echo "version=$(bun --version)" >> $GITHUB_OUTPUT

    - name: Cache Homebrew downloads (macOS)
      if: runner.os == 'macOS'
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/Homebrew/downloads
          ~/Library/Caches/Homebrew/Cask
        key: ${{ runner.os }}-${{ runner.arch }}-homebrew-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-homebrew-

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ runner.arch }}-bun-${{ steps.bun-version.outputs.version }}-node-modules-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-bun-${{ steps.bun-version.outputs.version }}-node-modules-

    - name: Cache bun install cache
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-cache-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-cache-

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile

    - name: Install ImageMagick (macOS)
      if: inputs.install-imagemagick == 'true' && runner.os == 'macOS'
      shell: bash
      run: |
        if command -v magick &>/dev/null; then
          echo "✅ ImageMagick already available"
        else
          echo "📦 Installing ImageMagick..."
          HOMEBREW_NO_AUTO_UPDATE=1 brew install imagemagick
        fi
        magick --version | head -1

    - name: Install ImageMagick (Linux)
      if: inputs.install-imagemagick == 'true' && runner.os == 'Linux'
      shell: bash
      run: |
        if command -v convert &>/dev/null; then
          echo "✅ ImageMagick already available"
        else
          echo "📦 Installing ImageMagick..."
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends imagemagick
        fi
        convert --version | head -1
