name: "Setup Cmux"
description: "Setup Bun and install dependencies with caching"
runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Cache Homebrew (macOS)
      if: runner.os == 'macOS'
      uses: actions/cache@v4
      with:
        path: ~/Library/Caches/Homebrew
        key: ${{ runner.os }}-brew-cache-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-brew-cache-

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile

    - name: Install ImageMagick (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        if ! brew list imagemagick &>/dev/null; then
          echo "📦 Installing ImageMagick..."
          time brew install imagemagick
        else
          echo "✅ ImageMagick already installed"
          brew list imagemagick --versions
        fi
        # Verify it's in PATH
        which magick
        magick --version | head -1

    - name: Install ImageMagick (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        if ! command -v convert &> /dev/null; then
          echo "Installing ImageMagick..."
          sudo apt-get update -qq
          sudo apt-get install -y imagemagick
        else
          echo "ImageMagick already installed"
        fi
