name: 'Setup Cmux'
description: 'Setup Bun and install dependencies with caching'
runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        # Bun's lockfile is bun.lockb; hash it for accurate cache busting
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile