#!/bin/bash
# Generate version.ts with git information

VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "unknown")
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > src/version.ts << EOF
// This file is auto-generated by scripts/generate-version.sh
// Do not edit manually

export const VERSION = {
  git: "${VERSION}",
  buildTime: "${TIMESTAMP}",
};
EOF

echo "Generated version.ts: ${VERSION} at ${TIMESTAMP}"
