name: "Setup Playwright"
description: "Install Playwright browsers with caching"
runs:
  using: "composite"
  steps:
    - name: Get Playwright version
      id: playwright-version
      shell: bash
      run: echo "version=$(bun x playwright --version | cut -d' ' -f2)" >> $GITHUB_OUTPUT

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install Playwright browsers and dependencies
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: bun x playwright install --with-deps
