name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-macos-arm64:
    name: Build macOS (ARM64)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build application
        run: bun run build

      - name: Package for macOS ARM64
        run: bun run dist:mac:arm64

      - name: Upload macOS ARM64 DMG
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-dmg
          path: release/*.dmg
          retention-days: 30
          if-no-files-found: error

  build-macos-x64:
    name: Build macOS (x64)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build application
        run: bun run build

      - name: Package for macOS x64
        run: bun run dist:mac:x64

      - name: Upload macOS x64 DMG
        uses: actions/upload-artifact@v4
        with:
          name: macos-x64-dmg
          path: release/*.dmg
          retention-days: 30
          if-no-files-found: error

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build application
        run: bun run build

      - name: Package for Linux
        run: bun run dist:linux

      - name: Upload Linux AppImage
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage
          path: release/*.AppImage
          retention-days: 30
          if-no-files-found: error
