name: Build

on:
  pull_request:
    branches: ["**"]
  merge_group:
  workflow_dispatch: # Allow manual triggering

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-cmux

      - name: Install ImageMagick
        run: brew install imagemagick

      - name: Setup code signing
        run: ./scripts/setup-macos-signing.sh
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          AC_APIKEY_P8_BASE64: ${{ secrets.AC_APIKEY_P8_BASE64 }}
          AC_APIKEY_ID: ${{ secrets.AC_APIKEY_ID }}
          AC_APIKEY_ISSUER_ID: ${{ secrets.AC_APIKEY_ISSUER_ID }}

      - name: Package for macOS
        run: make dist-mac

      - name: Upload macOS DMG (x64)
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg-x64
          path: release/*-x64.dmg
          retention-days: 30
          if-no-files-found: error

      - name: Upload macOS DMG (arm64)
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg-arm64
          path: release/*-arm64.dmg
          retention-days: 30
          if-no-files-found: error

  build-linux:
    name: Build Linux
    runs-on: ${{ github.repository_owner == 'coder' && 'depot-ubuntu-22.04-16' || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-cmux

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Package for Linux
        run: make dist-linux

      - name: Upload Linux AppImage
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage
          path: release/*.AppImage
          retention-days: 30
          if-no-files-found: error
