name: CI

on:
  pull_request:
    branches: ["**"]
  merge_group:

jobs:
  static-check:
    name: Static Checks (lint + typecheck + fmt)
    runs-on: ${{ github.repository_owner == 'coder' && 'depot-ubuntu-22.04-16' || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-cmux

      - name: Generate version file
        run: ./scripts/generate-version.sh

      - name: Cache shfmt
        id: cache-shfmt
        uses: actions/cache@v4
        with:
          path: ~/.local/bin/shfmt
          # We install latest via webinstall; reflect that in the cache key to avoid pinning mismatches
          key: ${{ runner.os }}-shfmt-latest
          restore-keys: |
            ${{ runner.os }}-shfmt-

      - name: Install shfmt
        if: steps.cache-shfmt.outputs.cache-hit != 'true'
        run: |
          curl -sS https://webinstall.dev/shfmt | bash

      - name: Add shfmt to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run static checks
        run: make -j3 static-check

  test:
    name: Test
    runs-on: ${{ github.repository_owner == 'coder' && 'depot-ubuntu-22.04-16' || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-cmux

      - name: Run tests
        run: make test-unit

  integration-test:
    name: Integration Tests
    runs-on: ${{ github.repository_owner == 'coder' && 'depot-ubuntu-22.04-16' || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-cmux

      - name: Run integration tests
        run: make test-integration
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

  e2e-test:
    name: End-to-End Tests
    runs-on: ${{ github.repository_owner == 'coder' && 'depot-ubuntu-22.04-16' || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-cmux

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Install Playwright runtime dependencies
        run: bun x playwright install-deps

      - name: Install Playwright browsers
        run: bun x playwright install --with-deps

      - name: Run e2e tests
        run: xvfb-run -a make test-e2e
        env:
          ELECTRON_DISABLE_SANDBOX: 1

  check-codex-comments:
    name: Check Codex Comments
    runs-on: ${{ github.repository_owner == 'coder' && 'depot-ubuntu-22.04-16' || 'ubuntu-latest' }}
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for unresolved Codex comments
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/check_codex_comments.sh ${{ github.event.pull_request.number }}

# Trigger CI run
